const { GoogleSpreadsheet } = require("google-spreadsheet");
const { JWT } = require("google-auth-library");
import { handleError, handleSuccess } from "../helpers/response";
import { xlsxParser } from "../util/xlsParser";
import fs from "fs";
const GOOGLE_SERVICE_ACCOUNT_EMAIL =
  "download-excel@excelserver.iam.gserviceaccount.com";
const GOOGLE_PRIVATE_KEY =
  "-----BEGIN PRIVATE KEY-----\nMIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQDKgqsPvYzO6FwB\ntp4N85nmXABGBm6VazAxJzJZK9/F+7ry7COwe18qGjuX/uBFk5r7mpAWQKVlRJnP\nKTnDPUwD99hN/nVG5K+Qv7TC9R916DJ/nxCD3aaKHHEFPvEHf9K4XcdVaXFKsB6s\n/WJurOJkP2rV3IzPDo0HqNobwx2bPyjXy6zt7CRIpMgNHBVLvzDudgXc/L/A8iXN\nhdZhiZ89FDqEDXcCua7zevj6bT2VAlLtihUNu4/Ui3gQ6m0/m6RLfnKmMxhcNt11\nHw6BgI8ZKuYOjK8Jm/VE/4KuJWOKX5TTpme+s3o1UUfEswXCbYID89AtOOSiYya9\nu5Yi0q4bAgMBAAECggEAMEFXwr3vriQXPH9IBVoNS6OTmxwQQMGUb7n/2NjID1TP\nNPCJBpY3VICAv9THmzyzew3XFL5dyxZAMmmH7pqOIQnvfJJMXtLCdRMBX01qrD1i\nvx9nn4xzEUj6s33OkHNogm8yPwuLp/j0rlMIoAfJQIsOCZzu3q4AdBlLs77YMLQ9\nH8IfBt+OY+dd2KPA58k1J2LdXo8MAf2Sqw3Ks5wOSZ7Wvewa+Gk/9n/X+cawUSR/\nI44yJnM5+33Udez3ol2Bq/IV39jQFZCW6S4Tka0iqoJfpH05WnTjEiy8nsCGs93y\nIlcOulExesJPkuufmjDb0z9YmNGg3KQ1Vn5Pp4e5mQKBgQDnkBYI68PhWCmpQh1b\nFjtEltx6+JHn3bOPTp8+ksP+Cl4Y6DEsQD2WdKY9+zn5XYrpHXLmuHdu2FL56zvn\nQJZgwdkUwwhPN7veuEBWGcsrHdAP0Gyl7nkU9oI028l30beevWH+5qe2+Gx0agYN\n0zfXkSuYe2CifZbHgTld+69S2QKBgQDf4bNZY1EVbuxqdFDa66OHnUcOsUwjZqpJ\nZ+slYwJJAFV9NUrje+r2iqdIEG0wd0mCMDJdgm4+TObIddYJnh6lzDBVHC26t/9a\nFThHaawfeTX3e0f2jfCqC4cNja/N2NMj5G37GoVA/zXy3aTFi65AeYAZdqVv9zmQ\nyfG/AwbIEwKBgHTnOxiZ3jQfzDiVFjjsClPgTcMPRqnmNUZ+DMsMUUIpfcPZRSnv\n7KfOkDbuZCBOZ1i081MjgbhGIe3mIkHnS4PhmXRv2fwUSRZxsplFQFquHGI/ePp0\nYFCC+s0wwI9rIuZS+ew0CivHUwmalR/ZqHF96qJ6dxjRipOB27Jk4+hRAoGAERue\nKOZ9+7VOO5RH2XLIPES4eVbzCoF94b4fKew28H0mCztXTaraeZx+y/L1ZQ64f0pP\njvW4luopeIgIoxOCJAlGaDqPBAWrbabRdiONE5qflRnGlgCis1vOJir9lC1NdSCv\nhtCv/heCd9yYCsBxwFuIfmmimru5mmbUIlSI4CECf2GLo/ZUiU/Om54yMxNwxlFa\nexQPw3owo/YEP1xbBdjIBXv9bI2N022orsgqa6/U487rFPG+MTL2yzIZoPuWuVsn\nplgMb9Dio40JnhQhe2jB7f3g+LFfYqecUXd15Rag34Qo4Q5aNQvU8RJEaPrfRyc7\nceEAbAOk/ugE4fz9Ggo=\n-----END PRIVATE KEY-----\n";
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: GOOGLE_PRIVATE_KEY,
  scopes: [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive.file",
  ],
});
export const parserExcel2Json = async (req, res) => {
  const { sheet_id_example, sheet_id_editor, sheet_id_data } = req.body;
  try {
    const doc_editor = new GoogleSpreadsheet(
      sheet_id_editor,
      serviceAccountAuth
    );
    const doc_example = new GoogleSpreadsheet(
      sheet_id_example,
      serviceAccountAuth
    );
    const doc_data = new GoogleSpreadsheet(sheet_id_data, serviceAccountAuth);
    await doc_editor.loadInfo();
    await doc_example.loadInfo();
    await doc_data.loadInfo();
    return handleSuccess(res, {}, "Thành công");
  } catch (err) {
    return handleError(res, "Lỗi không xác định", err);
  }
};
export const excelController = {
  parserExcel2Json,
};
