const { GoogleSpreadsheet } = require("google-spreadsheet");
const { JWT } = require("google-auth-library");
import { handleError, handleSuccess } from "../helpers/response";
import { xlsxParser } from "../util/xlsParser";
import fs from "fs";
const GOOGLE_SERVICE_ACCOUNT_EMAIL =
  "download-excel@hoclieu-cloud-storage.iam.gserviceaccount.com";
const GOOGLE_PRIVATE_KEY =
  "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCylnPEWlZrIiqQ\nuhS0yocKyH6rlEeRSqJoVYz7D6yp1Cfk1oiHilz5B58RRMGCLKaxmvmi7GiPqNO5\nL5XcRa/+Q1G+POuC7+koLYwVOUymmf8PEgGk/wDS/pSQxIAtQ7+UlhSP3hsg+/by\nAJz6AzapssDJw8O2f4do5U2kp89jxJxou4O3hv8dvS11S7msnMs6YApP9CPHfkyo\nscgzuYvm51OxPdFuf5/ej6ULxb+gHeIHZzzY2lj5MLgFumyjtXNSsZ26IOuQbTk+\nd4o68xYmmCCE9Xzx9jyogKlN5TJsjr8oqj+4uyV7vc58+Pae1ZOPcq9adGz32XoJ\ndCX0UI8hAgMBAAECggEAAe5G5g2Demufb0U3Fi12iGHFSScvNGViDDPOPxnK6DhN\nLkf5qHx7l5d9teQ1nYnhy1EFfVL7aOqJJSBcHoo+1juwVti7WO+tfcPrTCtHIRR7\nDv9xoYY+bNQ4MzilTvKjmpBvpw6zzKIeEqekytOte+gdCzljeetBoaXRVnQYKwgS\nIphzmME+eaoUlRrFFgn0OW5WP0NiQa95DysLaB98ZnmVZQQkSlmCNAh1HvUWdcR2\nXuKwek/AaZGHcZ4OcYJiRi8Ua0K/SfXxQ8VMkcjcAenWh0PLshaw9h+vi5+4OrSF\nNCOHePtSz368/A08Dkdo0tGXvMhPwGojD0RKcJhyqQKBgQDd4R0ZLQtX2wcDqdpc\n7fgM5dcILd/8Vkilfu/MDqGrIopIQUhvLWVXvTDmbQvDuQwwfTt2w7vXPPW04LkO\ntDMEMCIVw17jn3j6Oet7UvaAZ7GNlrZhZSW3db3QDXKsOVRkWqZbqoSrceRA8vWX\nHvVbgAK1kdjN3b/oeGS8tL8WGQKBgQDODQtyKL9I7sc8cMNqRb4D2Qlyw5heowB7\nlwPhjvrBHy1qH6FUaEleK4TWOdjM0dNF9KyZNHwjtdanvdZlEAtTouB8kKybEWcu\nJ7THJEpH0N8JpH+Vto5aa5k46ns37erqXb7mxsNXKawYkSzW1LCYU3QM24N6G1wL\nB7pTBiGSSQKBgDcIQc5fxMN6uOeotld8UpzoWQhXUInm4MfjjxievGyU+ZVoU833\nhX5Yl4tfmp5mBGb2eMxBShLdtNezMVM7ULgGND4PojZ09G2j9gs1jZxVm81Rh1Tq\n4Ir7ciPrYfjjk1H8xexQg+1+Jy4Q1Ocxr4uNWZ6tWQfeq12+lsXTUt3pAoGALrbS\nY31NcLGBxfgitZM+Mw0fkT866im2UE66eIa73tC8sRSetM434/ul0BOpTTY82d1Q\nzCMUCdyN39WwJ5Vtm/aPQm5iU32skNA7sfJOTN3T0xHSQxTyTRmb0UWHzfRIj/3U\n6+kgHEC8XY18RvBNYRt6cffKZQKS6YVE/tGjBtECgYEAi7nGPyVV7M+lh174nL2y\n1jTKe22K1/87P0RSaNzDBpnQXo/6YFHZTTXVQ7hKP3v+ipjTro3mu8ATbhxsZfLm\nPP4M0SbsVgZ+F3JIhWBQAIIXMtmEi+1Gnepia2u37qsu8WGbXPKoN5JgSVLnwjSr\n35rF3LHddtlasJ1zBDJLMNs=\n-----END PRIVATE KEY-----\n";
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: GOOGLE_PRIVATE_KEY,
  scopes: [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive.file",
  ],
});
export const parserExcel2Json = async (req, res) => {
  const { sheet_id } = req.body;
  try {
    const doc = new GoogleSpreadsheet(sheet_id, serviceAccountAuth);
    await doc.loadInfo();
    const xlsxBuffer = await doc.downloadAsXLSX();
    const file_name = new Date().toISOString();
    if (!fs.existsSync("./public/excel")) {
      await fs.mkdirSync("./public/excel");
    }
    const file_path = `./public/excel/${file_name}.xlsx`;
    await fs.writeFileSync(file_path, Buffer.from(xlsxBuffer));
    const json = { data: {} };
    await xlsxParser.run(file_path, json);
    fs.unlink(file_path, (err) => {
      if (err) {
        console.error(err);
      }
    });
    return handleSuccess(res, json, "Thành công");
  } catch (err) {
    return handleError(res, "Lỗi không xác định", err);
  }
};
export const excelController = {
  parserExcel2Json,
};
